[package]
name = "mvp"
version = "0.1.0"
edition = "2024"

[dependencies]
infer = "0.19.0"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["time", "process", "macros", "rt", "rt-multi-thread"] }
