[package]
name = "mvp"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
infer = "0.19.0"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["time", "process", "macros", "rt", "rt-multi-thread"] }
wayland-client = "0.31.11"
