name: Tag release
on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-cli:
    name: Build CLI program
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            crates
            Cargo.toml
      - name: see code (debug)
        run: |
          ls -la
      - name: install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: compile cli
        run: |
          cargo build --release --manifest-path crates/bg-cli/Cargo.toml
      - name: upload binary
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            crates/bg-cli/target/release/bg-cli
